//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;
using School.POCO;

namespace School.Model
{
    public partial class SchoolModelContainer : ObjectContext
    {
        public const string ConnectionString = "name=SchoolModelContainer";
        public const string ContainerName = "SchoolModelContainer";
    
        #region Constructors
    
        public SchoolModelContainer()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public SchoolModelContainer(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public SchoolModelContainer(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Course> Course
        {
            get { return _course  ?? (_course = CreateObjectSet<Course>("Course")); }
        }
        private ObjectSet<Course> _course;
    
        public ObjectSet<Trainee> Trainee
        {
            get { return _trainee  ?? (_trainee = CreateObjectSet<Trainee>("Trainee")); }
        }
        private ObjectSet<Trainee> _trainee;

        #endregion
    }
}
