//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace School.POCO
{
    public partial class Course
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual string Wording
        {
            get;
            set;
        }
    
        public virtual int NumberOfDays
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Trainee> Trainee
        {
            get
            {
                if (_trainee == null)
                {
                    var newCollection = new FixupCollection<Trainee>();
                    newCollection.CollectionChanged += FixupTrainee;
                    _trainee = newCollection;
                }
                return _trainee;
            }
            set
            {
                if (!ReferenceEquals(_trainee, value))
                {
                    var previousValue = _trainee as FixupCollection<Trainee>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupTrainee;
                    }
                    _trainee = value;
                    var newValue = value as FixupCollection<Trainee>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupTrainee;
                    }
                }
            }
        }
        private ICollection<Trainee> _trainee;

        #endregion
        #region Association Fixup
    
        private void FixupTrainee(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Trainee item in e.NewItems)
                {
                    if (!item.Course.Contains(this))
                    {
                        item.Course.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Trainee item in e.OldItems)
                {
                    if (item.Course.Contains(this))
                    {
                        item.Course.Remove(this);
                    }
                }
            }
        }

        #endregion
    }
}
